version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "serverless-api"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1jarlca899j2h"
s3_prefix = "serverless-api"
region = "eu-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
